// src/features/contact/components/Chat.tsx
import { useEffect, useRef } from "preact/hooks";
import { useStore } from "@nanostores/preact";
import { $isChatVisible } from "../lib/chatToggle";

const Chat = () => {
  const dialogRef = useRef<HTMLDialogElement>(null);
  const isVisible = useStore($isChatVisible);

  useEffect(() => {
    if (isVisible) {
      dialogRef.current?.show();
    } else {
      dialogRef.current?.close();
    }
  });

  return (
    <dialog ref={dialogRef} className="bg-red-dark fixed z-50 bottom-0">
      hello lol
    </dialog>
  );
};

export default Chat;

// src/features/contact/components/Chat.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { isChatOpen } from "../lib/chat.store";

  let dialog: HTMLDialogElement;

  onMount(() => {
    isChatOpen.subscribe((status) => {
      if (status) {
        dialog.show();
      } else {
        dialog.close();
      }
    });
  });
</script>

<dialog bind:this={dialog} class="bg-red-light bottom-0">hello lol</dialog>
